### ISSUE TITLE
SatDump crash when trying to decode NOAA19 audio file

### ISSUE THREAD

**Issue by Canaribou02** [SatDump/SatDump#881]
**Description of the issue**
Hello everyone, today i was trying to decode an audio file from NOAA19 which i recorded yesterday, but everytime i try to decode the audio, the progression bar arrive at 100% and suddenly SatDump close without error message and i don't know what to do.
So please help me !

**Hardware (SDR/PC/OS)**
RTL-SDR V3/ Laptop Asus Vivobook x509ja/ Windows 11
**Version (Eg, 1.0.0, CI Build 171)**
SatDump version 1.2.1
**Logs after the crash** (satdump.log from ~/.config/satdump or %appdata%\satdump)
[
[satdump-20241128T170827.log](https://github.com/user-attachments/files/17950359/satdump-20241128T170827.log)

**Other info (Eg, Screenshots) / Files useful for debugging (CADU, etc)**
This is before i tried to decode the audio
![satdumpdetail](https://github.com/user-attachments/assets/01e58f74-87e6-4ae3-a807-dcd61570b42c)
I can send other screenshots if needed

**Comment by JVital2013** [comment]
Hello!

This looks like the crash that was fixed at aedcd32. Please try again using the latest nightly: https://github.com/SatDump/SatDump/releases/tag/nightly

**Comment by Canaribou02** [comment]
Thank you for your answer ! But after try with the nightly version i still have the same problem.

**Comment by JVital2013** [comment]
Uh oh! Can you share the wav file? You may need to zip it up, or upload it to another site

**Comment by Canaribou02** [comment]
Here is the audio file: [https://we.tl/t-kM4YGUsMWX](url)
I already decode it with an another site and the image was pretty good.

**Comment by JVital2013** [comment]
Thanks! I just tested your file on the latest nightly, and it didn't crash, but it did hang. It's possible it will crash some systems. I'll get this fixed up

**Comment by Canaribou02** [comment]
Ok, thank you for your help !

**Comment by JVital2013** [comment]
This should now be fixed in the latest nightly. The error was caused by the code not properly handling when you don't set the start timestamp. It will now throw appropriate warnings, but there should be no negative side effects.

You can now decode the image from your wav, but if you don't mind, I have some feedback:

- Setting the start timestamp is highly recommended. Without that, SatDump doesn't know where the satellite is, and cannot produce the nice MCIR/MSA images with colored land/water.
- Your signal is too noisy to read calibration info, which means most of the composites cannot be generated even with the start timestamp. Antenna design and noise source removal is king here! You are close to a signal good enough to calibrate.
- Also, make sure there is no compression when recording, and that you are sampling enough spectrum - a bandwidth of 40 kHz is usually good. There's something funky going on with the strips on the left - some kind of "shadowing."
 Just why I bring this up!

Overall though, nice initial work!

![raw_sync](https://github.com/user-attachments/assets/238e87b3-24ca-4edb-8415-01e4ac333012)
